-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 11:40:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupodb
-- -----------------------------------------------------
-- New model for groupomania sql

-- -----------------------------------------------------
-- Schema groupodb
--
-- New model for groupomania sql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupodb` DEFAULT CHARACTER SET utf8 ;
USE `groupodb` ;

-- -----------------------------------------------------
-- Table `groupodb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupodb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `createdAt` VARCHAR(45) NOT NULL,
  `updatedAt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupodb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupodb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `text` VARCHAR(1000) NOT NULL,
  `updatedAt` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `createdAt` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupodb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupodb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupodb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(1000) NOT NULL,
  `createdAt` VARCHAR(45) NOT NULL,
  `updatedAt` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `posts_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_comments_posts1_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupodb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `groupodb`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupodb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupodb`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `posts_id`),
  INDEX `fk_users_has_posts_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_users_has_posts_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `groupodb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_posts_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `groupodb`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
